app/mrs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mrs_base.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('mrs_base/', include('mrs_base.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/mrs_base/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordChangeView
from mrs.settings import LOGOUT_REDIRECT_URL

from mrs_base.views import training, about, portfolio_index, portfolio, \
    casual, brutal, dandy, mystyle, mystyle2, logout, UserRegisterView, user_login,  \
    BlogNews, NewsCategory, ViewPost, AddPost, EditPost, podbor, podborcvety, AddComment, \
    Search, ViewProfile, EditProfilePage, AddProfileInformation, SettingsProfile, NewsTags, \
    ChangePasswordView

app_name = 'mrs_base'

urlpatterns = [
    path('training/', training, name='training'),
    path('about/', about, name='about'),
    path('portfolio_index/', portfolio_index, name='portfolio_index'),
    path('portfolio/', portfolio, name='portfolio'),
    path('casual/', casual, name='casual'),
    path('brutal/', brutal, name='brutal'),
    path('dandy/', dandy, name='dandy'),
    path('mystyle/', mystyle, name='mystyle'),
    path('mystyle2/', mystyle2, name='mystyle2'),
    path('login/', user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page=LOGOUT_REDIRECT_URL), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('blog/', BlogNews.as_view(), name='BlogNews'),
    path('blog/category/<int:topic_id>/', NewsCategory.as_view(), name='NewsCategory'),
    path('blog/tag/<int:tag_id>/', NewsTags.as_view(), name='NewsTags'),
    path('blog/news_post/<int:news_id>', ViewPost.as_view(), name='ViewPost'),
    path('blog/edit_post/<int:id>', EditPost.as_view(), name='EditPost'),
    path('add-post', AddPost.as_view(), name='AddPost'),
    path('podbor/', podbor, name='podbor'),
    path('podborcvety/', podborcvety, name='podborcvety'),
    path('add-comment/', AddComment.as_view(), name='AddComment'),
    path('blog/search/', Search.as_view(), name='Search'),
    path('profile/user/<username>', ViewProfile.as_view(), name='Profile'),
    path('profile/user/edit_profile_page/<int:user_id>', EditProfilePage.as_view(), name='EditProfilePage'),
    path('profile/user/add_profile_information/', AddProfileInformation.as_view(), name='AddProfileInformation'),
    path('profile/user/settings/', SettingsProfile.as_view(), name='SettingsProfile'),
    path('profile/user/settings/changepassword', ChangePasswordView.as_view(), name='ChangePassword'),
]

app/mrs_base/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms
from django.forms import widgets

from mrs_base.models import Category, News, Comment, Profile
from mrs_base.widgets import MyWidget

user = get_user_model()


class NewsForm(forms.ModelForm):
    is_published = forms.ChoiceField(choices=(('True', 'Да'), ('False', 'Нет')))

    class Meta:
        model = News
        fields = ('title', 'theme', 'tag', 'short_text', 'content', 'is_published', 'topic', 'photo')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'short_text': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'rows': 1, 'cols': 1}),
            'topic': forms.Select(),
            # 'photo': MyWidget()

        }


class EditNewsForm(forms.ModelForm):
    is_published = forms.ChoiceField(choices=(('True', 'Да'), ('False', 'Нет')))

    class Meta:
        model = News
        fields = ('title', 'theme', 'tag', 'short_text', 'content', 'is_published', 'topic', 'photo')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'short_text': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'rows': 1, 'cols': 1}),
            'topic': forms.Select(),

        }


class AddProfileInformation(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'telegram_nikname', 'mobile_phone', 'profile_pic')
        widgets = {
            'mobile_phone': forms.TextInput(attrs={'class': 'form-control'}),
            'telegram_nikname': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'rows': 1, 'cols': 1}),
        }


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'telegram_nikname', 'mobile_phone', 'profile_pic')
        widgets = {
            'mobile_phone': forms.TextInput(attrs={'class': 'form-control'}),
            'telegram_nikname': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'rows': 1, 'cols': 1}),
        }


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', 'author', 'post')


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    username = forms.CharField(label='Логин пользователя', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10'
    }))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'wrap-input100 validate-input m-b-10'
    }))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={
        'class': 'wrap-input100 validate-input m-b-10'
    }))


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'wrap-input100 validate-input m-b-10'
    }))


class UserSettingsForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    username = forms.CharField(max_length=100, label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    first_name = forms.CharField(max_length=100, label='Имя', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    last_name = forms.CharField(max_length=100, label='Фамилия', widget=forms.TextInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10',
    }))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10'
    }))


class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

    old_password = forms.CharField(max_length=100, label='Старый пароль', widget=forms.PasswordInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10', 'type': 'password'
    }))
    new_password1 = forms.CharField(max_length=100, label='Новый пароль', widget=forms.PasswordInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10', 'type': 'password'
    }))
    new_password2 = forms.CharField(max_length=100, label='Повторите новый пароль', widget=forms.PasswordInput(attrs={
        'class': 'wrap-input100 validate-input m-t-5 m-b-10', 'type': 'password'
    }))

app/mrs_base/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.db.models import Prefetch, Q
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from django.template import loader
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, View, UpdateView
from django.contrib.auth import login, logout

from .forms import UserRegisterForm, NewsForm, UserLoginForm, CommentsForm, EditProfileForm, AddProfileInformation, \
    UserSettingsForm, ChangePasswordForm, EditNewsForm
from mrs_base.models import News, Category, Comment, User, Profile, BlogTips, Themes, Tags


def index(request):
    template = loader.get_template('indexbase.html')
    return HttpResponse(template.render({}, request))


def training(request):
    template = loader.get_template('training.html')
    return HttpResponse(template.render({}, request))


def about(request):
    template = loader.get_template('about.html')
    return HttpResponse(template.render({}, request))


def portfolio_index(request):
    template = loader.get_template('portfolio-index.html')
    return HttpResponse(template.render({}, request))


def portfolio(request):
    template = loader.get_template('portfolio.html')
    return HttpResponse(template.render({}, request))


def casual(request):
    template = loader.get_template('casual.html')
    return HttpResponse(template.render({}, request))


def brutal(request):
    template = loader.get_template('brutal.html')
    return HttpResponse(template.render({}, request))


def dandy(request):
    template = loader.get_template('dandy.html')
    return HttpResponse(template.render({}, request))


def mystyle(request):
    template = loader.get_template('mystyle.html')
    return HttpResponse(template.render({}, request))


def mystyle2(request):
    template = loader.get_template('mystyle2.html')
    return HttpResponse(template.render({}, request))


@login_required
def podbor(request):
    template = loader.get_template('podbor.html')
    return HttpResponse(template.render({}, request))


@login_required
def podborcvety(request):
    template = loader.get_template('podborcvetov.html')
    return HttpResponse(template.render({}, request))


class BlogNews(ListView):
    model = News
    template_name = 'blog.html'
    context_object_name = 'news'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tips'] = BlogTips.objects.filter(is_published=True)
        return context

    def get_queryset(self):
        return News.objects.filter(theme=1, is_published=True)


class NewsCategory(ListView):
    model = News
    template_name = 'blog_category.html'
    context_object_name = 'news'
    allow_empty = False
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories_topic'] = Category.objects.get(pk=self.kwargs['topic_id'])
        return context

    def get_queryset(self):
        return News.objects.filter(topic_id=self.kwargs['topic_id'], is_published=True).select_related('topic')


class NewsTags(ListView):
    model = News
    template_name = 'blog_tag.html'
    context_object_name = 'news'
    allow_empty = False
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tags.objects.get(pk=self.kwargs['tag_id'])
        return context

    def get_queryset(self):
        return News.objects.filter(tag_id=self.kwargs['tag_id'], is_published=True)


class AddComment(View):

    def post(self, request, *args, **kwargs):
        print(request.POST)
        form = CommentsForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mrs_base:ViewPost', news_id=request.POST.get('post'))


class ViewPost(DetailView):
    model = News
    pk_url_kwarg = 'news_id'
    template_name = 'blog_post.html'
    context_object_name = 'news_item'

    def get_queryset(self):
        return News.objects.prefetch_related(
            Prefetch('comments', queryset=Comment.objects.all())
        )


class AddPost(CreateView):
    form_class = NewsForm
    template_name = 'add_post.html'
    login_url = '/'


class EditPost(UpdateView):
    model = News
    pk_url_kwarg = 'news_id'
    template_name = 'edit_post.html'
    context_object_name = 'news_item'
    form_class = EditNewsForm

    def get_object(self):
        return get_object_or_404(News, id=self.kwargs.get('id'))


def user_logout(request):
    if request.method == "POST":
        logout(request)
        return redirect('index')


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')
    else:
        form = UserLoginForm()
    template = loader.get_template('login.html')
    return HttpResponse(template.render({'form': form}, request))


class UserRegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'signup.html'
    success_url = reverse_lazy('index')


# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             messages.success(request, 'Вы успешно зарегистрированы!')
#             return redirect('index')
#         else:
#             messages.error(request, 'Ошибка регистрации!')
#     else:
#         form = UserRegisterForm()
#     template = loader.get_template('signup.html')
#     return HttpResponse(template.render({'form': form}, request))


class Search(ListView):
    model = News
    paginate_by = 5
    template_name = 'blog.html'
    context_object_name = 'news'

    def get_queryset(self):
        return News.objects.filter(Q(short_text__icontains=self.request.GET.get('q')) |
                                   Q(title__icontains=self.request.GET.get('q')))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = f'&q={self.request.GET.get("q")}'
        return context


class ViewProfile(DetailView):
    model = User
    pk_url_kwarg = 'username'
    template_name = 'profile.html'
    context_object_name = 'user'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))


class EditProfilePage(UpdateView):
    model = Profile
    pk_url_kwarg = 'user'
    template_name = 'edit_profile_page.html'
    context_object_name = 'profile'
    form_class = EditProfileForm

    def get_object(self):
        return get_object_or_404(Profile, user_id=self.kwargs.get('user_id'))


class AddProfileInformation(CreateView):
    model = Profile
    form_class = AddProfileInformation
    template_name = 'add_profile_information.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SettingsProfile(UpdateView):
    form_class = UserSettingsForm
    template_name = 'settings_profile.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse('mrs_base:Profile', kwargs={'username': self.request.user.username})


class ChangePasswordView(PasswordChangeView):
    form_class = ChangePasswordForm
    template_name = 'change_password.html'

    def get_success_url(self):
        return reverse('mrs_base:Profile', kwargs={'username': self.request.user.username})

app/mrs_base/templates/indexbase.html
{% extends "base.html" %}
{% load static %}

{% block scriptcustom %}
{% endblock %}

{% block content %}

    <!-- Intro Section
   ================================================== -->
    <section id="intro">

        <!-- Slideshow container -->
        <div class="slideshow-container">

            <!-- Full-width images with number and caption text -->
            <div class="mySlides fade">
                <img src="{% static "images/sliders/1.jpg" %}" style="width:100%">
                <div class="text">Caption Text</div>
            </div>

            <div class="mySlides fade">
                <img src="{% static "images/sliders/2.jpg" %}" style="width:100%">
                <div class="text">Caption Two</div>
            </div>

            <div class="mySlides fade">
                <img src="{% static "images/sliders/3.jpg" %}" style="width:100%">
                <div class="text">Caption Three</div>
            </div>

            <!-- Next and previous buttons -->
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>

        <!-- The dots/circles -->
        <div style="text-align:center">
            <span class="dot" onclick="currentSlide(1)"></span>
            <span class="dot" onclick="currentSlide(2)"></span>
            <span class="dot" onclick="currentSlide(3)"></span>
        </div>


    </section> <!-- Intro Section End-->

    <!-- Info Section
   ================================================== -->
    <section id="info">

        <div class="row">

            <div class="twelve columns align-center">
                <h1 class="color-blue">Зачем тебе одеваться стильно?</h1>
            </div>


            <div class="bgrid-quarters s-bgrid-halves">

                <div class="columns">
                    <h2>Пример.</h2>

                    <p>Наглядный пример того как можно стильно одеваться и подбирать наряд в соответствии с вашим типом
                        фигуры.
                    </p>
                </div>

                <div class="columns">
                    <h2>Самовыражение.</h2>

                    <p>Возможность самовыражения и приобретение уверенности в себе для людей с нестандартными
                        пропорциями в фигуре. Сегодня мир индустрии одежды подарил уверенность в себе даже очень полным
                        людям, ведь появилась масса коллекций как, например, для людей небольшого роста, так и для
                        полных.
                    </p>
                </div>

                <div class="columns s-first">
                    <h2>Внимание.</h2>

                    <p>Следуя моде вы всегда находитесь в центре внимания. Вы - главный объект внимания.
                    </p>
                </div>

                <div class="columns">
                    <h2>Уверенность.</h2>

                    <p>Следуя моде вы всегда чувствуете себя уверенно. Каждый новый образ который вы надели придает
                        уверенности, что пооложительно сказывается на вашей жизни!
                    </p>
                </div>

            </div>

        </div>

    </section> <!-- Info Section End-->

    <!-- Works Section
   ================================================== -->
    <section id="works">

        <div class="row">

            <div class="twelve columns align-center">
                <h1>Несколько стилей одежды которые могут быть вам по душе.</h1>
            </div>

            <div id="portfolio-wrapper" class="bgrid-quarters s-bgrid-halves">

                <div class="columns portfolio-item">
                    <div class="item-wrap">
                        <a href="{% url 'mrs_base:portfolio' %}">
                            <img alt="" src="{% static "images/Classic/1.jpg" %}">
                            <div class="overlay"></div>
                            <div class="link-icon"><i class="fa fa-link"></i></div>
                        </a>
                        <div class="portfolio-item-meta">
                            <h5><a href="{% url 'mrs_base:portfolio' %}">Классический</a></h5>
                            <p>Классичейский костюм</p>
                        </div>
                    </div>
                </div>

                <div class="columns portfolio-item">
                    <div class="item-wrap">
                        <a href="{% url 'mrs_base:casual' %}">
                            <img alt="" src="{% static "images/portfolio/Casual.jpg" %}">
                            <div class="overlay"></div>
                            <div class="link-icon"><i class="fa fa-link"></i></div>
                        </a>
                        <div class="portfolio-item-meta">
                            <h5><a href="{% url 'mrs_base:casual' %}">Кэжуал</a></h5>
                            <p>Более повседневный стиль</p>
                        </div>
                    </div>
                </div>

                <div class="columns portfolio-item s-first">
                    <div class="item-wrap">
                        <a href="{% url 'mrs_base:brutal' %}">
                            <img alt="" src="{% static "images/portfolio/brutal.jpg" %}">
                            <div class="overlay"></div>
                            <div class="link-icon"><i class="fa fa-link"></i></div>
                        </a>
                        <div class="portfolio-item-meta">
                            <h5><a href="{% url 'mrs_base:brutal' %}">Брутальный</a></h5>
                            <p>Характрена брутальная одежда</p>
                        </div>
                    </div>
                </div>

                <div class="columns portfolio-item">
                    <div class="item-wrap">
                        <a href="{% url 'mrs_base:dandy' %}">
                            <img alt="" src="{% static "images/portfolio/elegant.jpeg" %}">
                            <div class="overlay"></div>
                            <div class="link-icon"><i class="fa fa-link"></i></div>
                        </a>
                        <div class="portfolio-item-meta">
                            <h5><a href="{% url 'mrs_base:dandy' %}">Дэнди</a></h5>
                            <p>Внимание к деталям</p>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </section> <!-- Works Section End-->

    <!-- Journal Section
   ================================================== -->

    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>Как стильно одеваться мужчине?
                </h1>
                <iframe width="100%" height="450" src="https://www.youtube.com/embed/_Pzz4Z51Sm0"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
            </div>

        </div>

    </div> <!-- Page Title End-->



{% endblock %}

app/mrs_base/templates/podbor.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block scriptcustom %}
    <script type="text/javascript" src="{% static 'js/scriptpodbor.js' %}"></script>
{% endblock %}

{% block content %}
    <!-- Page Title
    ================================================== -->
    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>Подбор образа</h1>

                <p>Воспользуйтесь нашим генератором образов, чтобы не тратить время на поиск в интернете! Также вы
                    можете
                    образ, который вам понравится скачать себе! Приятного пользования!</p>
            </div>

        </div>

    </div> <!-- Page Title End-->

    <!-- Content
    ================================================== -->
    <div class="content-outer">
        <div class="row">
            <div class="ten columns centered text-center">
                <br>
                <h1>Выберите, что вам интересно и получите готовый образ!!!
                </h1>
                <br>

                <button onclick="myFunction4()" class="button">Лето</button>
                <button onclick="myFunction5()" class="button">Осень</button>
                <button onclick="myFunction6()" class="button">Зима</button>
                <button onclick="myFunction7()" class="button">Весна</button>

                <br>
                <br>

                <div class="entry-media" id="imagerand">
                    {#                    <img src="images/podbor/1.png" alt=""/>#}
                    <img src="{% static "images/podbor/1.png" %}" alt=""/>
                </div>

                <br>

                <div class="entry-media" id="imagerand">
                    <hr>
                    <h4>Адреса самых лучших магазинов одежды</h4>
                    <br>
                    <script type="text/javascript" charset="utf-8" async
                            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ad19a5733b67a1dca11662c1873b6e5e996fe9c22e34ddac920e565bbed9b49f8&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true">

                    </script>
                </div>
                <br>
            </div>
        </div>
    </div> <!-- Page Title End-->
{% endblock %}

app/mrs_base/templates/portfolio-index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <!-- Page Title
    ================================================== -->
    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>Мужские стили</h1>

                <p>На сегодняшний день мода представляет смешение разных стилей, которые появлялись и развивались в
                    течение
                    очень долгого времени. </p>
            </div>

        </div>

    </div> <!-- Page Title End-->

    <!-- Content
    ================================================== -->
    <div class="content-outer">

        <div id="page-content" class="row portfolio">

            <section class="entry cf">

                <div id="secondary" class="four columns entry-details">

                    <h1>Библиотека стилей.</h1>

                    <p class="lead">Давайте рассмотрим, какие стили на сегодняшний день пользуются популярностью среди
                        мужчин разного возраста и социального положения.</p>

                    <p>На сегодняшний день существует огромное количество разных стилей одежды. Самыми популярными из
                        них
                        являются</p>

                    <p>Классический.<br>
                        Кэжуал.<br>
                        Брутальный.<br>
                        Дэнди.</p>


                </div> <!-- Secondary End-->

                <div id="primary" class="eight columns portfolio-list">

                    <div id="portfolio-wrapper" class="bgrid-halves cf">

                        <div class="columns portfolio-item first">
                            <div class="item-wrap">
                                <a href="{% url 'mrs_base:portfolio' %}">
                                    <img alt="" src="{% static "images/portfolio/Classic.jpg" %}">
                                    <div class="overlay"></div>
                                    <div class="link-icon"><i class="fa fa-link"></i></div>
                                </a>
                                <div class="portfolio-item-meta">
                                    <h5><a href="{% url 'mrs_base:portfolio' %}">Классический</a></h5>
                                    <p>Строгие и формальные образы на основе костюмов</p>
                                </div>
                            </div>
                        </div>

                        <div class="columns portfolio-item">
                            <div class="item-wrap">
                                <a href="{% url 'mrs_base:casual' %}">
                                    <img alt="" src="{% static "images/portfolio/Casual.jpg" %}">
                                    <div class="overlay"></div>
                                    <div class="link-icon"><i class="fa fa-link"></i></div>
                                </a>
                                <div class="portfolio-item-meta">
                                    <h5><a href="{% url 'mrs_base:casual' %}">Casual</a></h5>
                                    <p>Более повседневный стиль</p>
                                </div>
                            </div>
                        </div>

                        <div class="columns portfolio-item first">
                            <div class="item-wrap">
                                <a href="{% url 'mrs_base:brutal' %}">
                                    <img alt="" src="{% static "images/portfolio/brutal.jpg" %}">
                                    <div class="overlay"></div>
                                    <div class="link-icon"><i class="fa fa-link"></i></div>
                                </a>
                                <div class="portfolio-item-meta">
                                    <h5><a href="{% url 'mrs_base:brutal' %}">Брутальный</a></h5>
                                    <p>Характрена брутальная одежда</p>
                                </div>
                            </div>
                        </div>

                        <div class="columns portfolio-item">
                            <div class="item-wrap">
                                <a href="{% url 'mrs_base:dandy' %}">
                                    <img alt="" src="{% static "images/portfolio/elegant.jpeg" %}">
                                    <div class="overlay"></div>
                                    <div class="link-icon"><i class="fa fa-link"></i></div>
                                </a>
                                <div class="portfolio-item-meta">
                                    <h5><a href="{% url 'mrs_base:dandy' %}">Dandy-style</a></h5>
                                    <p>Внимание к деталям</p>
                                </div>
                            </div>
                        </div>


                    </div>

                </div> <!-- primary end-->

            </section> <!-- end section -->

        </div> <!-- #page-content end-->

    </div> <!-- content End-->

    <!-- Tweets Section
    ================================================== -->

    <div id="page-title">

        <div class="row">

            <div class="ten columns centered text-center">
                <h1>Как найти свой стиль<span>.</span></h1>

                <iframe width="100%" height="450" src="https://www.youtube.com/embed/eFfh9hH9wr0" frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>

                <p>Очень важно найти именно свой стиль в одежде. Тот стиль в котором вы будете выглядеть на все
                    100% </p>
            </div>

        </div>

    </div> <!-- Page Title End-->

{% endblock %}